GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,DROP ON brokerdev.*  TO brokerdev@"%" IDENTIFIED BY 'sefryek';
GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,DROP,LOCK TABLES ON brokerdev.*  TO brokerdev@localhost IDENTIFIED BY 'sefryek';
